### ISSUE TITLE
ивент на проверку предмета в слоте

### ISSUE THREAD

**Issue by gggkal** [Astra-Interactive/IaHook#2]
Для пассивного восстановления маны у брони. Надо чтобы пассивно раз в X секунд при броне надетой давалось +X маны. И чтобы стакалось. То есть к примеру на каждой части брони 0.25 маны раз в 5 секунд. В такой случае при надетом фулл сете будет восстановление маны 1 в 5 секунд.
Также добавить проверку для предметов в руке

**Comment by makeevrserg** [comment]
Не работает с опкой
